// <auto-generated />
using System;
using ControleDespesa5;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ControleDespesa5.Migrations
{
    [DbContext(typeof(AplicationContext))]
    [Migration("20211013153126_atualizaBD202211013")]
    partial class atualizaBD202211013
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ControleDespesa5.Models.Despesa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Nomedespesa")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Despesa");
                });

            modelBuilder.Entity("ControleDespesa5.Models.MovimentosDR", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_MovimentosDR")
                        .HasColumnType("datetime2");

                    b.Property<string>("Desc_Despesa")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<int>("Duracao")
                        .HasColumnType("int");

                    b.Property<int>("Id_Despesa")
                        .HasColumnType("int");

                    b.Property<int>("Id_Receita")
                        .HasColumnType("int");

                    b.Property<int>("Id_Usario")
                        .HasColumnType("int");

                    b.Property<bool>("Repete")
                        .HasColumnType("bit");

                    b.Property<decimal>("Valor_Des")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Id_Usario");

                    b.ToTable("MovimentosDR");
                });

            modelBuilder.Entity("ControleDespesa5.Models.Receita", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<string>("Nomereceita")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Receita");
                });

            modelBuilder.Entity("ControleDespesa5.Models.MovimentosDR", b =>
                {
                    b.HasOne("ControleDespesa5.Models.Despesa", "Despesa")
                        .WithMany()
                        .HasForeignKey("Id_Usario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Despesa");
                });
#pragma warning restore 612, 618
        }
    }
}
